name: Test DNS

on: watch

jobs:
  build:
    if: github.actor == 'chkimes'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dump resolv.conf
      run: |
        cat /run/systemd/resolve/resolv.conf
        cat /etc/resolv.conf
    
    - name: ipconfig
      run: |
        ifconfig -a
      
    - name: VM metadata
      run: |
        curl -H "Metadata: true" http://169.254.169.254/metadata/instance?api-version=2019-06-01
        
    - name: nslookup
      run:
        nslookup mharder-formrec.cognitiveservices.azure.com
