name: CI (Windows)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '1 * * * *'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download cygwin
      run: |
        & cmd /c 'nslookup www.cygwin.com 2>&1'
        for ($i = 0; $i -lt 100; $i++)
        {
            try
            {
                (New-Object Net.WebClient).DownloadFile('http://www.cygwin.com/setup-x86_64.exe', 'setup-x86_64.exe')
                Write-Host "Downloaded file successfully"
            }
            catch
            {
                Write-Host "There is an error during package downloading:`n $_"
                Invoke-RestMethod -Headers @{"Metadata"="true"} -URI http://169.254.169.254/metadata/instance?api-version=2019-06-01 -Method get
                break
            }
        }
        & cmd /c 'nslookup www.cygwin.com 8.8.8.8 2>&1'
      shell: powershell
