name: CI (Windows)

on: watch

jobs:
  build:
    if: github.actor == 'chkimes'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test dns
      run: |
        cat /run/systemd/resolve/resolve.conf
        cat /etc/resolve.conf
