name: Test DNS

on: watch

jobs:
  build:
    if: github.actor == 'chkimes'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dump resolv.conf
      run: |
        echo ===== systemd resolv.conf =====
        cat /run/systemd/resolve/resolv.conf
        
        echo ===== etc resolv.conf =====
        cat /etc/resolv.conf
        
        sudo sed -i '/options edns0/d' /etc/resolv.conf
        echo ===== edited resolv.conf =====
        cat /etc/resolv.conf
        
        echo ===== usr lib resolv.conf =====
        cat /usr/lib/systemd/resolv.conf
        
        sudo sed -i '/options edns0/d' /usr/lib/systemd/resolv.conf
        echo ===== edited usr lib resolv.conf =====
        cat /usr/lib/systemd/resolv.conf
        
        sudo systemctl restart systemd-resolved
        
    
    - name: ipconfig
      run: |
        ifconfig -a
      
    - name: VM metadata
      run: |
        curl -H "Metadata: true" http://169.254.169.254/metadata/instance?api-version=2019-06-01
        
    - name: Start tcpdump
      run: |
        sudo tcpdump -D
        sudo tcpdump -i any -nn -w dns.cap &
        
    - name: nslookup default
      run:
        nslookup mharder-formrec.cognitiveservices.azure.com || true
    
    - name: nslookup 168.63.129.16
      run:
        nslookup mharder-formrec.cognitiveservices.azure.com 168.63.129.16 || true
        
    - name: dig EDNS 127.0.0.53
      run:
        dig +noall +answer mharder-formrec.cognitiveservices.azure.com @127.0.0.53

        
    - name: digNO EDNS 127.0.0.53
      run:
        dig +noedns +noall +answer mharder-formrec.cognitiveservices.azure.com @127.0.0.53

    - name: dig EDNS 168.63.129.16
      run:
        dig +noall +answer mharder-formrec.cognitiveservices.azure.com @168.63.129.16
        
    - name: dig NO EDNS 168.63.129.16
      run:
        dig +noedns +noall +answer mharder-formrec.cognitiveservices.azure.com @168.63.129.16

    - name: Kill tcpdump
      run: |
        sleep 1
        sudo kill -2 $(ps -e | pgrep tcpdump)
        
    - name: Upload to file.io
      run: |
        zip dns.zip dns.cap
        ls -l
        sudo curl -F 'file=@dns.zip' https://file.io
